### ISSUE TITLE
improve site loading speed | SEO

### ISSUE THREAD

**Issue by thetillhoff** [enforge-de/enforge.de#5]
- [ ] initial page with loader only, then load actual content afterwards (they block page load)
- [ ] put js at bottom of page
- [ ] add alt-url for js-packages
- [ ] add description meta tag
- [x] set lang attribute
- [x] set xss header Content-Security-Policy
- [x] use css link instead of @import (parallelism)
- [x] set an X-Frame-Options header to disable usage in iframes
- [ ] add robots.txt
- [x] remove duplicated css classes (maybe not possible)
- [x] add favicon
- [x] don't use !important in css (-> semantic ui is the problem here)
- [x] disable mime-type-sniffing with X-Content-Type-Options
- [ ] set Expires header for semantic ui sass min css & main js
- [ ] add integrity attribute to external sources
- [x] cloudflare > jsdelivr
- [x] many colors are only used once
- [ ] add noscript tag
- [x] integrate best practices from https://learn.jquery.com/performance/

**Comment by tillhoff** [comment]
(self)hosted > cloudflare > jsdelivr

**Comment by tillhoff** [comment]
> * [ ]  initial page with loader only, then load actual content afterwards (they block page load)
           DEPRECATED due to fast loading speed
> * [ ]  put js at bottom of page
           DEPRECATED due to no js on page
> * [ ]  add alt-url for js-packages
> * [ ]  add description meta tag
           DEPRECATED due to unneccarity
> * [x]  set lang attribute
> * [x]  set xss header Content-Security-Policy
> * [ ]  use css link instead of @import (parallelism)
> * [x]  set an X-Frame-Options header to disable usage in iframes
> * [ ]  add robots.txt
> * [x]  remove duplicated css classes (maybe not possible)
> * [x]  add favicon
> * [x]  don't use !important in css (-> semantic ui is the problem here)
> * [x]  disable mime-type-sniffing with X-Content-Type-Options
> * [ ]  set Expires header for semantic ui sass min css & main js
> * [ ]  add integrity attribute to external sources
           DEPRECATED due to no external files
> * [x]  cloudflare > jsdelivr
> * [x]  many colors are only used once
> * [ ]  add noscript tag
           DEPRECATED due to no js on page
> * [x]  integrate best practices from https://learn.jquery.com/performance/

**Comment by tillhoff** [comment]
> 
> 
> > * [x]   initial page with loader only, then load actual content afterwards (they block page load)
> >   DEPRECATED due to fast loading speed
> > * [x]   put js at bottom of page
> >   DEPRECATED due to no js on page
> > * [x]   add alt-url for js-packages
> >   DEPRECATED no js-packages
> > * [x]   add description meta tag
> >   DEPRECATED due to unneccarity
> > * [x]   set lang attribute
> > * [x]   set xss header Content-Security-Policy
> > * [x]   use css link instead of @import (parallelism)
> >   DEPRECATED no external css files, only critical css which is embedded for speed reasons
> > * [x]   set an X-Frame-Options header to disable usage in iframes
> > * [ ]   add robots.txt
> > * [x]   remove duplicated css classes (maybe not possible)
> > * [x]   add favicon
> > * [x]   don't use !important in css (-> semantic ui is the problem here)
> > * [x]   disable mime-type-sniffing with X-Content-Type-Options
> > * [x]   set Expires header for semantic ui sass min css & main js
> >   DEPRECATED no such files
> > * [x]   add integrity attribute to external sources
> >   DEPRECATED due to no external files
> > * [x]   cloudflare > jsdelivr
> > * [x]   many colors are only used once
> > * [x]   add noscript tag
> >   DEPRECATED due to no js on page
> > * [x]   integrate best practices from https://learn.jquery.com/performance/

**Comment by thetillhoff** [comment]
done
